# Generated by Django 5.2.15 on 2026-06-05 22:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=160)),
                ('requires_approval', models.BooleanField(default=False)),
                ('require_change_reason', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['project__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=120)),
                ('name', models.CharField(max_length=180)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('running', 'Running'), ('paused', 'Paused'), ('stopped', 'Stopped')], default='draft', max_length=20)),
                ('config', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=120)),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('value_type', models.CharField(choices=[('boolean', 'Boolean'), ('string', 'String'), ('number', 'Number'), ('json', 'JSON')], max_length=20)),
                ('archived', models.BooleanField(default=False)),
                ('rules', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['project__name', 'key'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExperimentResultSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_count', models.PositiveIntegerField(default=0)),
                ('conversion_count', models.PositiveIntegerField(default=0)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_snapshots', to='django_feature_flags.experiment')),
            ],
        ),
        migrations.AddField(
            model_name='experiment',
            name='flag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiments', to='django_feature_flags.featureflag'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=120)),
                ('reason', models.TextField(blank=True)),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='django_feature_flags.environment')),
                ('flag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='django_feature_flags.featureflag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('proposed_change', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='django_feature_flags.environment')),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='django_feature_flags.featureflag')),
            ],
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=120)),
                ('name', models.CharField(max_length=180)),
                ('metric_type', models.CharField(choices=[('conversion', 'Conversion'), ('funnel', 'Funnel'), ('guardrail', 'Guardrail')], max_length=20)),
                ('event_name', models.CharField(max_length=120)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='django_feature_flags.featureflag')),
            ],
        ),
        migrations.AddField(
            model_name='experiment',
            name='guardrail_metrics',
            field=models.ManyToManyField(blank=True, related_name='guardrail_experiments', to='django_feature_flags.metric'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='primary_metric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='django_feature_flags.metric'),
        ),
        migrations.AddField(
            model_name='featureflag',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='django_feature_flags.project'),
        ),
        migrations.AddField(
            model_name='environment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environments', to='django_feature_flags.project'),
        ),
        migrations.CreateModel(
            name='SDKKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('secret_hash', models.CharField(max_length=128, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sdk_keys', to='django_feature_flags.environment')),
            ],
            options={
                'ordering': ['environment__project__name', 'environment__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=120)),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='django_feature_flags.project')),
            ],
            options={
                'ordering': ['project__name', 'key'],
            },
        ),
        migrations.CreateModel(
            name='SegmentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conditions', models.JSONField(default=list)),
                ('exclude', models.BooleanField(default=False)),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='django_feature_flags.segment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=80)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('value', models.JSONField()),
                ('is_default', models.BooleanField(default=False)),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='django_feature_flags.featureflag')),
            ],
            options={
                'ordering': ['flag__key', 'key'],
            },
        ),
        migrations.CreateModel(
            name='TargetingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('conditions', models.JSONField(default=list)),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targeting_rules', to='django_feature_flags.featureflag')),
                ('variation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='django_feature_flags.variation')),
            ],
            options={
                'ordering': ['flag__key', 'priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FlagState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=False)),
                ('rollout', models.JSONField(blank=True, default=dict)),
                ('emergency_override', models.JSONField(blank=True, default=dict)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flag_states', to='django_feature_flags.environment')),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='django_feature_flags.featureflag')),
                ('default_variation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='django_feature_flags.variation')),
            ],
            options={
                'ordering': ['environment__project__name', 'environment__name', 'flag__key'],
            },
        ),
        migrations.CreateModel(
            name='ExperimentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveIntegerField(default=0)),
                ('holdout', models.BooleanField(default=False)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='django_feature_flags.experiment')),
                ('variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiment_allocations', to='django_feature_flags.variation')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('evaluation', 'Evaluation'), ('impression', 'Impression'), ('conversion', 'Conversion'), ('custom', 'Custom')], max_length=20)),
                ('context_key', models.CharField(blank=True, max_length=180)),
                ('metric_key', models.CharField(blank=True, max_length=120)),
                ('value', models.FloatField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='django_feature_flags.environment')),
                ('flag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='django_feature_flags.featureflag')),
                ('variation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='django_feature_flags.variation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='metric',
            constraint=models.UniqueConstraint(fields=('flag', 'key'), name='dff_unique_metric_key_per_flag'),
        ),
        migrations.AddConstraint(
            model_name='experiment',
            constraint=models.UniqueConstraint(fields=('flag', 'key'), name='dff_unique_experiment_key_per_flag'),
        ),
        migrations.AddConstraint(
            model_name='featureflag',
            constraint=models.UniqueConstraint(fields=('project', 'key'), name='dff_unique_flag_key_per_project'),
        ),
        migrations.AddConstraint(
            model_name='environment',
            constraint=models.UniqueConstraint(fields=('project', 'key'), name='dff_unique_environment_key_per_project'),
        ),
        migrations.AddConstraint(
            model_name='segment',
            constraint=models.UniqueConstraint(fields=('project', 'key'), name='dff_unique_segment_key_per_project'),
        ),
        migrations.AddConstraint(
            model_name='variation',
            constraint=models.UniqueConstraint(fields=('flag', 'key'), name='dff_unique_variation_key_per_flag'),
        ),
        migrations.AddConstraint(
            model_name='flagstate',
            constraint=models.UniqueConstraint(fields=('flag', 'environment'), name='dff_unique_flag_state_per_environment'),
        ),
    ]
