# Generated by Django 4.2.7 on 2026-06-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_feature_flags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flagstate',
            name='targeting',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
